sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.4.2"
      env: TOXENV=lint
    - python: "3.4.2"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
  # allow_failures:
  #   - python: "3.5"
  #     env: TOXENV=typing

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
language: python
script: travis_wait tox
after_success: coverall