sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.8"
      env: TOXENV=flake8
    - python: "3.8"
      env: TOXENV=pydocstyle
    - python: "3.8"
      env: TOXENV=pylint
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38

cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox coveralls
language: python
script: travis_wait tox
after_success:
  - coveralls
